logging:
  config: classpath:logback.xml  #日志配置文件
  level:
    com.example.practice.dao: trace  #打印日志级别

#配置微服务地址
url:
  #订单微服务的地址
  orderUrl: http://localhost:8002
  # 用户微服务的地址
  userUrl: http://localhost:8003
  # 购物车微服务的地址
  shoppingUrl: http://localhost:8004

spring:
  profiles:
    active: dev  #选择开发环境
  thymeleaf:
    cache: false  #关闭Thymeleaf缓存
  datasource:
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnect
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000


#数据库地址
datasource:
  url: localhost:3306/sboottest

mybatis:
  type-aliases-package: com.example.practice.entity # 指定别名设置的包为所有entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml