logging:
  config: classpath:logback.xml  #日志配置文件
  level:
    com.example.practice.dao: trace  #打印日志级别

#配置微服务地址
url:
  #订单微服务的地址
  orderUrl: http://localhost:8002
  # 用户微服务的地址
  userUrl: http://localhost:8003
  # 购物车微服务的地址
  shoppingUrl: http://localhost:8004

spring:
  profiles:
    active: dev  #选择开发环境
  thymeleaf:
    cache: false  #关闭Thymeleaf缓存
  datasource:
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnect
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
#    password: M9Ncehx92#$Redis
    connect-timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000

#数据库地址
datasource:
  url: localhost:3306/sboottest

mybatis:
  type-aliases-package: com.example.practice.entity # 指定别名设置的包为所有entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml